personality_table = {
    "Warrior": {
        # Below is a sample of how to store multiple personalities with percentages.
        # This data is taken from your wiki table for the Warrior class (Male & Female).
        # Each key is a tuple of (Gender, PrimaryStat, SecondaryStat, Range),
        # and each value is a list of (PersonalityName, Percentage).
        
        #------------------ MALE ------------------#
        ("Male", "Strength", "Any", "≥11"): [
            ("Paragon", 66.67),
            ("Meathead", 33.33),
        ],
        ("Male", "Strength", "Any", "7–10"): [
            ("Meathead", 44.44),
            ("Idealist", 33.33),
            ("Thug", 22.22),
        ],
        ("Male", "Strength", "Any", "≤6"): [
            ("Sore Loser", 37.50),
            ("Daredevil", 31.25),
            ("Klutz", 31.25),
        ],
        ("Male", "Strength", "Any", "≤6"): [
            ("Gourmand", 40.00),
            ("Thug", 40.00),
            ("Lothario", 20.00),
        ],
        ("Male", "Strength", "Any", "≤6"): [
            ("Everyman", 27.78),
            ("Straight Arrow", 22.22),
            ("Free Spirit", 16.67),
            ("Lothario", 16.67),
            ("Lout", 16.67),
        ],
        ("Male", "Agility", "Any", "≥12"): [
            ("Acrobat", 42.86),
            ("Bat out of Hell", 42.86),
            ("Daredevil", 14.29),
        ],
        ("Male", "Agility", "Any", "7–11"): [
            ("Scatterbrain", 34.78),
            ("Acrobat", 26.09),
            ("Sore Loser", 21.74),
            ("Narcissist", 17.39),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Idealist", 33.33),
            ("Lone Wolf", 33.33),
            ("Thug", 33.33),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Everyman", 34.48),
            ("Klutz", 20.69),
            ("Show-Off", 20.69),
            ("Socialite", 13.79),
            ("Crybaby", 10.34),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Slippery devil", 50.00),
            ("Clown", 37.50),
            ("Contrarian", 12.50),
        ],
        ("Male", "Resilience", "Any", "≥10"): [
            ("Ironclad", 50.00),
            ("Tough Cookie", 50.00),
        ],
        ("Male", "Resilience", "Any", "6–9"): [
            ("Drudge", 28.57),
            ("Mule", 28.57),
            ("Plugger", 28.57),
            ("Lothario", 14.29),
        ],
        ("Male", "Resilience", "Any", "≤5"): [
            ("Gourmand", 38.46),
            ("Meathead", 38.46),
            ("Free Spirit", 23.08),
        ],
        ("Male", "Resilience", "Any", "≤5"): [
            ("Everyman", 29.41),
            ("Lazybones", 17.65),
            ("Meddler", 17.65),
            ("Shrinking Violet", 17.65),
            ("Straight Arrow", 17.65),
        ],
        ("Male", "Wisdom", "Any", "≥10"): [
            ("Contrarian", 44.44),
            ("Daydreamer", 22.22),
            ("Egghead", 22.22),
            ("Wit", 11.11),
        ],
        ("Male", "Wisdom", "Any", "6–9"): [
            ("Daydreamer", 33.33),
            ("Show-Off", 33.33),
            ("Wimp", 33.33),
        ],
        ("Male", "Wisdom", "Any", "≤5"): [
            ("Everyman", 26.67),
            ("Clown", 20.00),
            ("Good Egg", 20.00),
            ("Spoilt Brat", 20.00),
            ("Lout", 13.33),
        ],
        ("Male", "Luck", "Any", "≥12"): [
            ("Lucky devil", 80.00),
            ("Happy Camper", 20.00),
        ],
        ("Male", "Luck", "Any", "7–11"): [
            ("Happy camper", 50.00),
            ("Daydreamer", 25.00),
            ("Lazybones", 25.00),
        ],
        ("Male", "Luck", "Any", "≤6"): [
            ("Everyman", 23.53),
            ("Clown", 17.65),
            ("Lout", 17.65),
            ("Show-Off", 17.65),
            ("Spoilt Brat", 17.65),
            ("Klutz", 5.88),
        ],

        #------------------ FEMALE ------------------#
        ("Female", "Strength", "Any", "≥11"): [
            ("Paragon", 50.00),
            ("Amazon", 25.00),
            ("Meathead", 25.00),
        ],
        ("Female", "Strength", "Any", "7–10"): [
            ("Meathead", 33.33),
            ("Idealist", 25.00),
            ("Tomboy", 25.00),
            ("Thug", 16.67),
        ],
        ("Female", "Strength", "Any", "≤6"): [
            ("Tomboy", 33.33),
            ("Sore Loser", 25.00),
            ("Daredevil", 20.83),
            ("Klutz", 20.83),
        ],
        ("Female", "Strength", "Any", "≤6"): [
            ("Gourmand", 40.00),
            ("Thug", 40.00),
            ("Amazon", 20.00),
        ],
        ("Female", "Strength", "Any", "≤6"): [
            ("Everyman", 33.33),
            ("Straight Arrow", 26.67),
            ("Free Spirit", 20.00),
            ("Lout", 20.00),
        ],
        ("Female", "Agility", "Any", "≥12"): [
            ("Acrobat", 42.86),
            ("Bat Out of Hell", 42.86),
            ("Daredevil", 14.29),
        ],
        ("Female", "Agility", "Any", "7–11"): [
            ("Scatterbrain", 34.78),
            ("Acrobat", 26.09),
            ("Sore Loser", 21.74),
            ("Narcissist", 17.39),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Idealist", 25.00),
            ("Lone Wolf", 25.00),
            ("Thug", 25.00),
            ("Tomboy", 25.00),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Everyman", 34.48),
            ("Klutz", 20.69),
            ("Show-Off", 20.69),
            ("Socialite", 13.79),
            ("Crybaby", 10.34),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Slippery Devil", 50.00),
            ("Clown", 37.50),
            ("Contrarian", 12.50),
        ],
        ("Female", "Resilience", "Any", "≥10"): [
            ("Ironclad", 50.00),
            ("Tough Cookie", 50.00),
        ],
        ("Female", "Resilience", "Any", "6–9"): [
            ("Drudge", 33.33),
            ("Mule", 33.33),
            ("Plugger", 33.33),
        ],
        ("Female", "Resilience", "Any", "≤5"): [
            ("Gourmand", 38.46),
            ("Meathead", 38.46),
            ("Free Spirit", 23.08),
        ],
        ("Female", "Resilience", "Any", "≤5"): [
            ("Everyman", 29.41),
            ("Lazybones", 17.65),
            ("Meddler", 17.65),
            ("Shrinking Violet", 17.65),
            ("Straight Arrow", 17.65),
        ],
        ("Female", "Wisdom", "Any", "≥10"): [
            ("Contrarian", 44.44),
            ("Daydreamer", 22.22),
            ("Egghead", 22.22),
            ("Wit", 11.11),
        ],
        ("Female", "Wisdom", "Any", "6–9"): [
            ("Princess", 30.77),
            ("Daydreamer", 23.08),
            ("Show-Off", 23.08),
            ("Wimp", 23.08),
        ],
        ("Female", "Wisdom", "Any", "≤5"): [
            ("Everyman", 26.67),
            ("Clown", 20.00),
            ("Spoilt Brat", 20.00),
            ("Lout", 13.33),
        ],
        ("Female", "Luck", "Any", "≥12"): [
            ("Princess", 80.00),
            ("Happy Camper", 20.00),
        ],
        ("Female", "Luck", "Any", "7–11"): [
            ("Happy Camper", 50.00),
            ("Daydreamer", 25.00),
            ("Lazybones", 25.00),
        ],
        ("Female", "Luck", "Any", "≤6"): [
            ("Everyman", 23.53),
            ("Clown", 17.65),
            ("Lout", 17.65),
            ("Show-Off", 17.65),
            ("Spoilt Brat", 17.65),
            ("Klutz", 5.88),
        ],
    },
    "Martial Artist": {
        # Add the Martial Artist data here.
        ("Male", "Strength", "Any", "≥11"): [
            ("Paragon", 66.67),
            ("Meathead", 33.33),
        ],
        ("Male", "Strength", "Any", "7–10"): [
            ("Meathead", 44.44),
            ("Idealist", 33.33),
            ("Thug", 22.22),
        ],
        ("Male", "Strength", "Any", "≤6"): [
            ("Sore Loser", 37.50),
            ("Daredevil", 31.25),
            ("Klutz", 31.25),
        ],
        ("Male", "Strength", "Any", "≤6"): [
            ("Gourmand", 40.00),
            ("Thug", 40.00),
            ("Lothario", 20.00),
        ],
        ("Male", "Strength", "Any", "≤6"): [
            ("Everyman", 27.78),
            ("Straight Arrow", 22.22),
            ("Free Spirit", 16.67),
            ("Lothario", 16.67),
            ("Lout", 16.67),
        ],
        ("Male", "Agility", "Any", "≥11"): [
            ("Bat out of Hell", 80.00),
            ("Acrobat", 10.00),
            ("Daredevil", 10.00),
        ],
        ("Male", "Agility", "Any", "7–10"): [
            ("Lone Wolf", 37.50),
            ("Acrobat", 25.00),
            ("Scatterbrain", 25.00),
            ("Daredevil", 12.50),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Idealist", 37.50),
            ("Sore Loser", 37.50),
            ("Show-Off", 25.00),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Drudge", 30.00),
            ("Idealist", 30.00),
            ("Contrarian", 20.00),
            ("Lothario", 20.00),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Everyman", 30.77),
            ("Lone Wolf", 23.08),
            ("Crybaby", 15.38),
            ("Daredevil", 15.38),
            ("Daydreamer", 15.38),
        ],
        ("Male", "Resilience", "Any", "≥10"): [
            ("Ironclad", 50.00),
            ("Tough Cookie", 50.00),
        ],
        ("Male", "Resilience", "Any", "6–9"): [
            ("Drudge", 28.57),
            ("Mug", 28.57),
            ("Plugger", 28.57),
            ("Lothario", 14.29),
        ],
        ("Male", "Resilience", "Any", "≤5"): [
            ("Gourmand", 38.46),
            ("Meathead", 38.46),
            ("Free Spirit", 23.08),
        ],
        ("Male", "Resilience", "Any", "≤5"): [
            ("Everyman", 29.41),
            ("Lazybones", 17.65),
            ("Meddler", 17.65),
            ("Shrinking Violet", 17.65),
            ("Straight Arrow", 17.65),
        ],
        ("Male", "Wisdom", "Any", "≥10"): [
            ("Contrarian", 44.44),
            ("Daydreamer", 22.22),
            ("Egghead", 22.22),
            ("Wit", 11.11),
        ],
        ("Male", "Wisdom", "Any", "6–9"): [
            ("Daydreamer", 33.33),
            ("Show-Off", 33.33),
            ("Wimp", 33.33),
        ],
        ("Male", "Wisdom", "Any", "≤5"): [
            ("Everyman", 26.67),
            ("Clown", 20.00),
            ("Good Egg", 20.00),
            ("Spoilt Brat", 20.00),
            ("Lout", 13.33),
        ],
        ("Male", "Luck", "Any", "≥12"): [
            ("Lucky Devil", 80.00),
            ("Happy Camper", 20.00),
        ],
        ("Male", "Luck", "Any", "7–11"): [
            ("Happy camper", 25.00),
            ("Daydreamer", 25.00),
            ("Lazybones", 25.00),
        ],
        ("Male", "Luck", "Any", "≤6"): [
            ("Everyman", 23.53),
            ("Clown", 17.65),
            ("Lout", 17.65),
            ("Show-Off", 17.65),
            ("Spoilt Brat", 17.65),
            ("Klutz", 5.88),
        ],

        ("Female", "Strength", "Any", "≥11"): [
            ("Paragon", 50.00),
            ("Amazon", 25.00),
            ("Meathead", 25.00),
        ],
        ("Female", "Strength", "Any", "7–10"): [
            ("Meathead", 33.33),
            ("Idealist", 25.00),
            ("Tomboy", 25.00),
            ("Thug", 16.67),
        ],
        ("Female", "Strength", "Any", "≤6"): [
            ("Tomboy", 33.33),
            ("Sore Loser", 25.00),
            ("Daredevil", 20.83),
            ("Klutz", 20.83),
        ],
        ("Female", "Strength", "Any", "≤6"): [
            ("Gourmand", 40.00),
            ("Thug", 40.00),
            ("Amazon", 20.00),
        ],
        ("Female", "Strength", "Any", "≤6"): [
            ("Everyman", 33.33),
            ("Straight Arrow", 26.67),
            ("Free Spirit", 20.00),
            ("Lout", 20.00),
        ],
        ("Female", "Agility", "Any", "≥11"): [
            ("Bat out of Hell", 80.00),
            ("Acrobat", 10.00),
            ("Daredevil", 10.00),
        ],
        ("Female", "Agility", "Any", "7–10"): [
            ("Lone Wolf", 37.50),
            ("Acrobat", 25.00),
            ("Scatterbrain", 25.00),
            ("Daredevil", 12.50),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Idealist", 27.27),
            ("Sore Loser", 27.27),
            ("Tomboy", 27.27),
            ("Show-Off", 18.18),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Drudge", 37.50),
            ("Idealist", 37.50),
            ("Contrarian", 25.00),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Everyman", 30.77),
            ("Lone Wolf", 23.08),
            ("Crybaby", 15.38),
            ("Daredevil", 15.38),
            ("Daydreamer", 15.38),
        ],
        ("Female", "Resilience", "Any", "≥10"): [
            ("Ironclad", 50.00),
            ("Tough Cookie", 50.00),
        ],
        ("Female", "Resilience", "Any", "6–9"): [
            ("Drudge", 33.33),
            ("Mule", 33.33),
            ("Plugger", 33.33),
        ],
        ("Female", "Resilience", "Any", "≤5"): [
            ("Gourmand", 38.46),
            ("Meathead", 38.46),
            ("Free Spirit", 23.08),
        ],
        ("Female", "Resilience", "Any", "≤5"): [
            ("Everyman", 29.41),
            ("Lazybones", 17.65),
            ("Meddler", 17.65),
            ("Shrinking Violet", 17.65),
            ("Straight Arrow", 17.65),
        ],
        ("Female", "Wisdom", "Any", "≥10"): [
            ("Contrarian", 44.44),
            ("Daydreamer", 22.22),
            ("Egghead", 22.22),
            ("Wit", 11.11),
        ],
        ("Female", "Wisdom", "Any", "6–9"): [
            ("Princess", 30.77),
            ("Daydreamer", 23.08),
            ("Show-Off", 23.08),
            ("Wimp", 23.08),
        ],
        ("Female", "Wisdom", "Any", "≤5"): [
            ("Everyman", 26.67),
            ("Clown", 20.00),
            ("Good Egg", 20.00),
            ("Spoilt Brat", 20.00),
            ("Lout", 20.00),
        ],
        ("Female", "Luck", "Any", "≥12"): [
            ("Princess", 80.00),
            ("Happy Camper", 20.00),
        ],
        ("Female", "Luck", "Any", "7–11"): [
            ("Happy Camper", 50.00),
            ("Daydreamer", 25.00),
            ("Lazybones", 25.00),
        ],
        ("Female", "Luck", "Any", "≤6"): [
            ("Everyman", 23.53),
            ("Clown", 17.65),
            ("Lout", 17.65),
            ("Show-Off", 17.65),
            ("Spoilt Brat", 17.65),
            ("Klutz", 14.29),
        ],
    },
    "Priest": {
        #------------------ MALE ------------------#
        ("Male", "Strength", "Any", "≥11"): [
            ("Meathead", 57.14),
            ("Daredevil", 42.86),
        ],
        ("Male", "Strength", "Any", "7–10"): [
            ("Meathead", 30.00),
            ("Meddler", 30.00),
            ("Idealist", 20.00),
            ("Mule", 20.00),
        ],
        ("Male", "Strength", "Any", "≤6"): [
            ("Everyman", 36.36),
            ("Good Egg", 18.18),
            ("Lout", 18.18),
            ("Straight Arrow", 18.18),
            ("Lazybones", 9.09),
        ],
        ("Male", "Strength", "Any", "≤6"): [
            ("Plugger", 36.36),
            ("Drudge", 27.27),
            ("Gourmand", 18.18),
            ("Narcissist", 18.18),
        ],
        ("Male", "Strength", "Any", "≤6"): [
            ("Socialite", 30.00),
            ("Sore Loser", 30.00),
            ("Show-Off", 20.00),
            ("Wimp", 20.00),
        ],
        ("Male", "Agility", "Any", "≥8"): [
            ("Acrobat", 37.50),
            ("Slipper Devil", 37.50),
            ("Scatterbrain", 25.00),
        ],
        ("Male", "Agility", "Any", "≤7"): [
            ("Klutz", 37.50),
            ("Sore Loser", 37.50),
            ("Show-Off", 25.00),
        ],
        ("Male", "Agility", "Any", "≤7"): [
            ("Everyman", 34.78),
            ("Daydreamer", 26.09),
            ("Spoilt Brat", 17.39),
            ("Lout", 13.04),
            ("Wimp", 8.70),
        ],
        ("Male", "Agility", "Any", "≤7"): [
            ("Egghead", 50.00),
            ("Clown", 25.00),
            ("Crybaby", 25.00),
        ],
        ("Male", "Resilience", "Any", "≥11"): [
            ("Drudge", 33.33),
            ("Ironclad", 33.33),
            ("Toug Cookie", 33.33),
        ],
        ("Male", "Resilience", "Any", "6–10"): [
            ("Drudge", 37.50),
            ("Mule", 25.00),
            ("Plugger", 25.00),
            ("Lothario", 12.50),
        ],
        ("Male", "Resilience", "Any", "≤5"): [
            ("Everyman", 28.57),
            ("Lout", 21.43),
            ("Wimp", 21.43),
            ("Free Spirit", 14.29),
            ("Socialite", 14.29),
        ],
        ("Male", "Resilience", "Any", "≤5"): [
            ("Good Egg", 37.50),
            ("Meddler", 37.50),
            ("Sore Loser", 25.00),
        ],
        ("Male", "Wisdom", "Any", "≥10"): [
            ("Genius", 75.00),
            ("Wit", 25.00),
        ],
        ("Male", "Wisdom", "Any", "6–9"): [
            ("Slippery Devil", 33.33),
            ("Wit", 22.22),
            ("Daydreamer", 16.67),
            ("Egghead", 16.67),
            ("Wimp", 11.11),
        ],
        ("Male", "Wisdom", "Any", "≤5"): [
            ("Everyman", 26.67),
            ("Crybaby", 20.00),
            ("Good Egg", 13.33),
            ("Socialite", 13.33),
            ("Spoilt Brat", 13.33),
            ("Straight Arrow", 13.33),
        ],
        ("Male", "Luck", "Any", "≥12"): [
            ("Lucky Devil", 80.00),
            ("Happy Camper", 20.00),
        ],
        ("Male", "Luck", "Any", "6–11"): [
            ("Happy Camper", 50.00),
            ("Lazybones", 25.00),
            ("Lout", 12.50),
            ("Spoilt Brat", 12.50),
        ],
        ("Male", "Luck", "Any", "≤5"): [
            ("Everyman", 27.03),
            ("Crybaby", 16.22),
            ("Show-Off", 16.22),
            ("Shrinking Violet", 16.22),
            ("Wimp", 13.51),
            ("Klutz", 10.81),
        ],

        #------------------ FEMALE ------------------#
        ("Female", "Strength", "Any", "≥11"): [
            ("Meathead", 40.00),
            ("Amazon", 30.00),
            ("Daredevil", 30.00),
        ],
        ("Female", "Strength", "Any", "7–10"): [
            ("Meathead", 30.00),
            ("Meddler", 30.00),
            ("Idealist", 20.00),
            ("Mule", 20.00),
        ],
        ("Female", "Strength", "Any", "≤6"): [
            ("Everyman", 30.77),
            ("Good Egg", 15.38),
            ("Lout", 15.38),
            ("Straight Arrow", 15.38),
            ("Tomboy", 15.38),
            ("Lazybones", 7.69),
        ],
        ("Female", "Strength", "Any", "≤6"): [
            ("Plugger", 36.36),
            ("Drudge", 27.27),
            ("Gourmand", 18.18),
            ("Narcissist", 18.18),
        ],
        ("Female", "Strength", "Any", "≤6"): [
            ("Socialite", 30.00),
            ("Sore Loser", 30.00),
            ("Show-Off", 20.00),
            ("Wimp", 20.00),
        ],
        ("Female", "Agility", "Any", "≥8"): [
            ("Acrobat", 37.50),
            ("Slippery Devil", 37.50),
            ("Scatterbrain", 25.00),
        ],
        ("Female", "Agility", "Any", "≤7"): [
            ("Klutz", 37.50),
            ("Sore Loser", 37.50),
            ("Show-Off", 25.00),
        ],
        ("Female", "Agility", "Any", "≤7"): [
            ("Everyman", 34.78),
            ("Daydreamer", 26.09),
            ("Spoilt Brat", 17.39),
            ("Lout", 13.04),
            ("Wimp", 8.70),
        ],
        ("Female", "Agility", "Any", "≤7"): [
            ("Vamp", 50.00),
            ("Egghead", 25.00),
            ("Clown", 12.50),
            ("Crybaby", 12.50),
        ],
        ("Female", "Resilience", "Any", "≥11"): [
            ("Drudge", 33.33),
            ("Ironclad", 33.33),
            ("Tough Cookie", 33.33),
        ],
        ("Female", "Resilience", "Any", "6–10"): [
            ("Drudge", 42.86),
            ("Mule", 28.57),
            ("Plugger", 28.57),
        ],
        ("Female", "Resilience", "Any", "≤5"): [
            ("Everyman", 28.57),
            ("Lout", 21.43),
            ("Wimp", 21.43),
            ("Free Spirit", 14.29),
            ("Socialite", 14.29),
        ],
        ("Female", "Resilience", "Any", "≤5"): [
            ("Good Egg", 27.27),
            ("Meddler", 27.27),
            ("Vamp", 27.27),
            ("Sore Loser", 18.18),
        ],
        ("Female", "Wisdom", "Any", "≥10"): [
            ("Genius", 75.00),
            ("Wit", 25.00),
        ],
        ("Female", "Wisdom", "Any", "6–9"): [
            ("Slippery Devil", 33.33),
            ("Wit", 22.22),
            ("Daydreamer", 16.67),
            ("Egghead", 16.67),
            ("Wimp", 11.11),
        ],
        ("Female", "Wisdom", "Any", "≤5"): [
            ("Everyman", 26.67),
            ("Crybaby", 20.00),
            ("Good Egg", 13.33),
            ("Socialite", 13.33),
            ("Spoilt Brat", 13.33),
            ("Straight Arrow", 13.33),
        ],
        ("Female", "Luck", "Any", "≥12"): [
            ("Princess", 80.00),
            ("Happy Camper", 20.00),
        ],
        ("Female", "Luck", "Any", "6–11"): [
            ("Happy Camper", 50.00),
            ("Lazybones", 25.00),
            ("Lout", 12.50),
            ("Spoilt Brat", 12.50),
        ],
        ("Female", "Luck", "Any", "≤5"): [
            ("Everyman", 27.03),
            ("Crybaby", 16.22),
            ("Show-Off", 16.22),
            ("Shrinking Violet", 16.22),
            ("Wimp", 13.51),
            ("Klutz", 10.81),
        ],
    },
    "Mage": {
        #------------------ MALE ------------------#
        ("Male", "Strength", "Any", "≥11"): [
            ("Meathead", 57.14),
            ("Daredevil", 42.86),
        ],
        ("Male", "Strength", "Any", "7–10"): [
            ("Meathead", 30.00),
            ("Meddler", 30.00),
            ("Idealist", 20.00),
            ("Mule", 20.00),
        ],
        ("Male", "Strength", "Any", "≤6"): [
            ("Everyman", 36.36),
            ("Good Egg", 18.18),
            ("Lout", 18.18),
            ("Straight Arrow", 18.18),
            ("Lazybones", 9.09),
        ],
        ("Male", "Strength", "Any", "≤6"): [
            ("Plugger", 36.36),
            ("Drudge", 27.27),
            ("Gourmand", 18.18),
            ("Narcissist", 18.18),
        ],
        ("Male", "Strength", "Any", "≤6"): [
            ("Socialite", 30.00),
            ("Sore Loser", 30.00),
            ("Show-Off", 20.00),
            ("Wimp", 20.00),
        ],
        ("Male", "Agility", "Any", "≥8"): [
            ("Acrobat", 37.50),
            ("Slipper Devil", 37.50),
            ("Scatterbrain", 25.00),
        ],
        ("Male", "Agility", "Any", "≤7"): [
            ("Klutz", 37.50),
            ("Sore Loser", 37.50),
            ("Show-Off", 25.00),
        ],
        ("Male", "Agility", "Any", "≤7"): [
            ("Everyman", 34.78),
            ("Daydreamer", 26.09),
            ("Spoilt Brat", 17.39),
            ("Lout", 13.04),
            ("Wimp", 8.70),
        ],
        ("Male", "Agility", "Any", "≤7"): [
            ("Egghead", 50.00),
            ("Clown", 25.00),
            ("Crybaby", 25.00),
        ],
        ("Male", "Resilience", "Any", "≥11"): [
            ("Drudge", 33.33),
            ("Ironclad", 33.33),
            ("Toug Cookie", 33.33),
        ],
        ("Male", "Resilience", "Any", "6–10"): [
            ("Drudge", 37.50),
            ("Mule", 25.00),
            ("Plugger", 25.00),
            ("Lothario", 12.50),
        ],
        ("Male", "Resilience", "Any", "≤5"): [
            ("Everyman", 28.57),
            ("Lout", 21.43),
            ("Wimp", 21.43),
            ("Free Spirit", 14.29),
            ("Socialite", 14.29),
        ],
        ("Male", "Resilience", "Any", "≤5"): [
            ("Good Egg", 37.50),
            ("Meddler", 37.50),
            ("Sore Loser", 25.00),
        ],
        ("Male", "Wisdom", "Any", "≥10"): [
            ("Genius", 75.00),
            ("Wit", 25.00),
        ],
        ("Male", "Wisdom", "Any", "6–9"): [
            ("Slippery Devil", 33.33),
            ("Wit", 22.22),
            ("Daydreamer", 16.67),
            ("Egghead", 16.67),
            ("Wimp", 11.11),
        ],
        ("Male", "Wisdom", "Any", "≤5"): [
            ("Everyman", 26.67),
            ("Crybaby", 20.00),
            ("Good Egg", 13.33),
            ("Socialite", 13.33),
            ("Spoilt Brat", 13.33),
            ("Straight Arrow", 13.33),
        ],
        ("Male", "Luck", "Any", "≥12"): [
            ("Lucky Devil", 80.00),
            ("Happy Camper", 20.00),
        ],
        ("Male", "Luck", "Any", "6–11"): [
            ("Happy Camper", 50.00),
            ("Lazybones", 25.00),
            ("Lout", 12.50),
            ("Spoilt Brat", 12.50),
        ],
        ("Male", "Luck", "Any", "≤5"): [
            ("Everyman", 27.03),
            ("Crybaby", 16.22),
            ("Show-Off", 16.22),
            ("Shrinking Violet", 16.22),
            ("Wimp", 13.51),
            ("Klutz", 10.81),
        ],

        #------------------ FEMALE ------------------#
        ("Female", "Strength", "Any", "≥11"): [
            ("Meathead", 40.00),
            ("Amazon", 30.00),
            ("Daredevil", 30.00),
        ],
        ("Female", "Strength", "Any", "7–10"): [
            ("Meathead", 30.00),
            ("Meddler", 30.00),
            ("Idealist", 20.00),
            ("Mule", 20.00),
        ],
        ("Female", "Strength", "Any", "≤6"): [
            ("Everyman", 30.77),
            ("Good Egg", 15.38),
            ("Lout", 15.38),
            ("Straight Arrow", 15.38),
            ("Tomboy", 15.38),
            ("Lazybones", 7.69),
        ],
        ("Female", "Strength", "Any", "≤6"): [
            ("Plugger", 36.36),
            ("Drudge", 27.27),
            ("Gourmand", 18.18),
            ("Narcissist", 18.18),
        ],
        ("Female", "Strength", "Any", "≤6"): [
            ("Socialite", 30.00),
            ("Sore Loser", 30.00),
            ("Show-Off", 20.00),
            ("Wimp", 20.00),
        ],
        ("Female", "Agility", "Any", "≥8"): [
            ("Acrobat", 37.50),
            ("Slippery Devil", 37.50),
            ("Scatterbrain", 25.00),
        ],
        ("Female", "Agility", "Any", "≤7"): [
            ("Klutz", 37.50),
            ("Sore Loser", 37.50),
            ("Show-Off", 25.00),
        ],
        ("Female", "Agility", "Any", "≤7"): [
            ("Everyman", 34.78),
            ("Daydreamer", 26.09),
            ("Spoilt Brat", 17.39),
            ("Lout", 13.04),
            ("Wimp", 8.70),
        ],
        ("Female", "Agility", "Any", "≤7"): [
            ("Vamp", 50.00),
            ("Egghead", 25.00),
            ("Clown", 12.50),
            ("Crybaby", 12.50),
        ],
        ("Female", "Resilience", "Any", "≥11"): [
            ("Drudge", 33.33),
            ("Ironclad", 33.33),
            ("Tough Cookie", 33.33),
        ],
        ("Female", "Resilience", "Any", "6–10"): [
            ("Drudge", 42.86),
            ("Mule", 28.57),
            ("Plugger", 28.57),
        ],
        ("Female", "Resilience", "Any", "≤5"): [
            ("Everyman", 28.57),
            ("Lout", 21.43),
            ("Wimp", 21.43),
            ("Free Spirit", 14.29),
            ("Socialite", 14.29),
        ],
        ("Female", "Resilience", "Any", "≤5"): [
            ("Good Egg", 27.27),
            ("Meddler", 27.27),
            ("Vamp", 27.27),
            ("Sore Loser", 18.18),
        ],
        ("Female", "Wisdom", "Any", "≥10"): [
            ("Genius", 75.00),
            ("Wit", 25.00),
        ],
        ("Female", "Wisdom", "Any", "6–9"): [
            ("Slippery Devil", 33.33),
            ("Wit", 22.22),
            ("Daydreamer", 16.67),
            ("Egghead", 16.67),
            ("Wimp", 11.11),
        ],
        ("Female", "Wisdom", "Any", "≤5"): [
            ("Everyman", 26.67),
            ("Crybaby", 20.00),
            ("Good Egg", 13.33),
            ("Socialite", 13.33),
            ("Spoilt Brat", 13.33),
            ("Straight Arrow", 13.33),
        ],
        ("Female", "Luck", "Any", "≥12"): [
            ("Princess", 80.00),
            ("Happy Camper", 20.00),
        ],
        ("Female", "Luck", "Any", "6–11"): [
            ("Happy Camper", 50.00),
            ("Lazybones", 25.00),
            ("Lout", 12.50),
            ("Spoilt Brat", 12.50),
        ],
        ("Female", "Luck", "Any", "≤5"): [
            ("Everyman", 27.03),
            ("Crybaby", 16.22),
            ("Show-Off", 16.22),
            ("Shrinking Violet", 16.22),
            ("Wimp", 13.51),
            ("Klutz", 10.81),
        ],
    },
    "Thief": {
        #------------------ MALE ------------------#
        ("Male", "Strength", "Any", "≥11"): [
            ("Idealist", 35.29),
            ("Meathead", 35.29),
            ("Sore Loser", 29.41),
        ],
        ("Male", "Strength", "Any", "≤10"): [
            ("Acrobat", 37.50),
            ("Clown", 37.50),
            ("Scatterbrain", 25.00),
        ],
        ("Male", "Strength", "Any", "≤10"): [
            ("Daredevil", 55.56),
            ("Thug", 44.44),
        ],
        ("Male", "Strength", "Any", "≤10"): [
            ("Lone Wolf", 44.44),
            ("Genius", 33.33),
            ("Slippery Devil", 22.22),
        ],
        ("Male", "Strength", "Any", "≤10"): [
            ("Everyman", 28.57),
            ("Narcissist", 21.43),
            ("Crybaby", 14.29),
            ("Daydreamer", 14.29),
            ("Socialite", 14.29),
            ("Spoilt Brat", 7.14),
        ],

        ("Male", "Agility", "Any", "≥11"): [
            ("Bat out of Hell", 80.00),
            ("Acrobat", 10.00),
            ("Daredevil", 10.00),
        ],
        ("Male", "Agility", "Any", "7–10"): [
            ("Lone Wolf", 37.50),
            ("Acrobat", 25.00),
            ("Scatterbrain", 25.00),
            ("Daredevil", 12.50),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Idealist", 37.50),
            ("Sore Loser", 37.50),
            ("Show-Off", 25.00),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Drudge", 30.00),
            ("Idealist", 30.00),
            ("Contrarian", 20.00),
            ("Lothario", 20.00),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Everyman", 30.77),
            ("Lone Wolf", 23.08),
            ("Crybaby", 15.38),
            ("Daredevil", 15.38),
            ("Daydreamer", 15.38),
        ],

        ("Male", "Resilience", "Any", "≥11"): [
            ("Gourmand", 33.33),
            ("Ironclad", 33.33),
            ("Toug Cookie", 33.33),
        ],
        ("Male", "Resilience", "Any", "6–10"): [
            ("Drudge", 33.33),
            ("Gourmand", 27.78),
            ("Mule", 22.22),
            ("Lothario", 16.67),
        ],
        ("Male", "Resilience", "Any", "≤5"): [
            ("Thug", 60.00),
            ("Daredevil", 40.00),
        ],
        ("Male", "Resilience", "Any", "≤5"): [
            ("Clown", 25.00),
            ("Everyman", 25.00),
            ("Lazybones", 25.00),
            ("Daydreamer", 12.50),
            ("Lone Wolf", 12.50),
        ],

        ("Male", "Wisdom", "Any", "≥10"): [
            ("Genius", 80.00),
            ("Wit", 20.00),
        ],
        ("Male", "Wisdom", "Any", "6–9"): [
            ("Slippery Devil", 40.00),
            ("Wit", 26.67),
            ("Egghead", 20.00),
            ("Show-Off", 13.33),
        ],
        ("Male", "Wisdom", "Any", "≤5"): [
            ("Everyman", 25.81),
            ("Lone Wolf", 19.35),
            ("Meddler", 19.35),
            ("Klutz", 12.90),
            ("Plugger", 12.90),
            ("Daydreamer", 9.68),
        ],

        ("Male", "Luck", "Any", "≥12"): [
            ("Lucky Devil", 80.00),
            ("Happy Camper", 20.00),
        ],
        ("Male", "Luck", "Any", "6–11"): [
            ("Happy Camper", 27.27),
            ("Free Spirit", 18.18),
            ("Meddler", 18.18),
            ("Narcissist", 18.18),
            ("Spoilt Brat", 18.18),
        ],
        ("Male", "Luck", "Any", "≤5"): [
            ("Everyman", 25.00),
            ("Crybaby", 18.75),
            ("Lout", 18.75),
            ("Good Egg", 12.50),
            ("Show-Off", 12.50),
            ("Straight Arrow", 12.50),
        ],

        #------------------ FEMALE ------------------#
        ("Female", "Strength", "Any", "≥11"): [
            ("Idealist", 26.09),
            ("Meathead", 26.09),
            ("Tomboy", 26.09),
            ("Sore Loser", 21.74),
        ],
        ("Female", "Strength", "Any", "≤10"): [
            ("Acrobat", 37.50),
            ("Clown", 37.50),
            ("Scatterbrain", 25.00),
        ],
        ("Female", "Strength", "Any", "≤10"): [
            ("Amazon", 40.00),
            ("Daredevil", 33.33),
            ("Thug", 26.67),
        ],
        ("Female", "Strength", "Any", "≤10"): [
            ("Lone Wolf", 44.44),
            ("Genius", 33.33),
            ("Slippery Devil", 22.22),
        ],
        ("Female", "Strength", "Any", "≤10"): [
            ("Everyman", 28.57),
            ("Narcissist", 21.43),
            ("Crybaby", 14.29),
            ("Daydreamer", 14.29),
            ("Socialite", 14.29),
            ("Spoilt Brat", 7.14),
        ],

        ("Female", "Agility", "Any", "≥11"): [
            ("Bat out of Hell", 80.00),
            ("Acrobat", 10.00),
            ("Daredevil", 10.00),
        ],
        ("Female", "Agility", "Any", "7–10"): [
            ("Lone Wolf", 37.50),
            ("Acrobat", 25.00),
            ("Scatterbrain", 25.00),
            ("Daredevil", 12.50),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Idealist", 27.27),
            ("Sore Loser", 27.27),
            ("Tomboy", 27.27),
            ("Show-Off", 18.18),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Drudge", 37.50),
            ("Idealist", 37.50),
            ("Contrarian", 25.00),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Everyman", 30.77),
            ("Lone Wolf", 23.08),
            ("Crybaby", 15.38),
            ("Daredevil", 15.38),
            ("Daydreamer", 15.38),
        ],

        ("Female", "Resilience", "Any", "≥11"): [
            ("Gourmand", 33.33),
            ("Ironclad", 33.33),
            ("Tough Cookie", 33.33),
        ],
        ("Female", "Resilience", "Any", "6–10"): [
            ("Drudge", 40.00),
            ("Gourmand", 33.33),
            ("Mule", 26.67),
        ],
        ("Female", "Resilience", "Any", "≤5"): [
            ("Thug", 60.00),
            ("Daredevil", 40.00),
        ],
        ("Female", "Resilience", "Any", "≤5"): [
            ("Clown", 20.00),
            ("Everyman", 20.00),
            ("Lazybones", 20.00),
            ("Vamp", 20.00),
            ("Daydreamer", 10.00),
            ("Lone Wolf", 10.00),
        ],

        ("Female", "Wisdom", "Any", "≥10"): [
            ("Genius", 80.00),
            ("Wit", 20.00),
        ],
        ("Female", "Wisdom", "Any", "6–9"): [
            ("Slippery Devil", 40.00),
            ("Wit", 26.67),
            ("Egghead", 20.00),
            ("Show-Off", 13.33),
        ],
        ("Female", "Wisdom", "Any", "≤5"): [
            ("Everyman", 25.81),
            ("Lone Wolf", 19.35),
            ("Meddler", 19.35),
            ("Klutz", 12.90),
            ("Plugger", 12.90),
            ("Daydreamer", 9.68),
        ],

        ("Female", "Luck", "Any", "≥12"): [
            ("Happy Camper", 100.00),
        ],
        ("Female", "Luck", "Any", "6–11"): [
            ("Happy Camper", 27.27),
            ("Free Spirit", 18.18),
            ("Meddler", 18.18),
            ("Narcissist", 18.18),
            ("Spoilt Brat", 18.18),
        ],
        ("Female", "Luck", "Any", "≤5"): [
            ("Everyman", 25.00),
            ("Crybaby", 18.75),
            ("Lout", 18.75),
            ("Good Egg", 12.50),
            ("Show-Off", 12.50),
            ("Straight Arrow", 12.50),
        ],
    },
    "Merchant": {
        #------------------ MALE ------------------#
        ("Male", "Strength", "Any", "≥11"): [
            ("Idealist", 35.29),
            ("Meathead", 35.29),
            ("Sore Loser", 29.41),
        ],
        ("Male", "Strength", "Any", "≤10"): [
            ("Acrobat", 37.50),
            ("Clown", 37.50),
            ("Scatterbrain", 25.00),
        ],
        ("Male", "Strength", "Any", "≤10"): [
            ("Daredevil", 55.56),
            ("Thug", 44.44),
        ],
        ("Male", "Strength", "Any", "≤10"): [
            ("Lone Wolf", 44.44),
            ("Genius", 33.33),
            ("Slippery Devil", 22.22),
        ],
        ("Male", "Strength", "Any", "≤10"): [
            ("Everyman", 28.57),
            ("Narcissist", 21.43),
            ("Crybaby", 14.29),
            ("Daydreamer", 14.29),
            ("Socialite", 14.29),
            ("Spoilt Brat", 25.00),
        ],

        ("Male", "Agility", "Any", "≥12"): [
            ("Acrobat", 42.86),
            ("Bat out of Hell", 42.86),
            ("Daredevil", 14.29),
        ],
        ("Male", "Agility", "Any", "7–11"): [
            ("Scatterbrain", 34.78),
            ("Acrobat", 26.09),
            ("Sore Loser", 21.74),
            ("Narcissist", 17.39),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Idealist", 33.33),
            ("Lone Wolf", 33.33),
            ("Thug", 33.33),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Everyman", 34.48),
            ("Klutz", 20.69),
            ("Show-Off", 20.69),
            ("Socialite", 13.79),
            ("Crybaby", 10.34),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Slippery Devil", 50.00),
            ("Clown", 37.50),
            ("Contrarian", 12.50),
        ],

        ("Male", "Resilience", "Any", "≥10"): [
            ("Ironclad", 50.00),
            ("Tough Cookie", 50.00),
        ],
        ("Male", "Resilience", "Any", "6–9"): [
            ("Drudge", 28.57),
            ("Mule", 28.57),
            ("Plugger", 28.57),
            ("Lothario", 14.29),
        ],
        ("Male", "Resilience", "Any", "≤5"): [
            ("Gourmand", 38.46),
            ("Meathead", 38.46),
            ("Free Spirit", 23.08),
        ],
        ("Male", "Resilience", "Any", "≤5"): [
            ("Everyman", 29.41),
            ("Lazybones", 17.65),
            ("Meddler", 17.65),
            ("Shrinking Violet", 17.65),
            ("Straight Arrow", 17.65),
        ],

        ("Male", "Wisdom", "Any", "≥10"): [
            ("Genius", 80.00),
            ("Wit", 20.00),
        ],
        ("Male", "Wisdom", "Any", "6–9"): [
            ("Slippery Devil", 40.00),
            ("Wit", 26.67),
            ("Egghead", 20.00),
            ("Show-Off", 13.33),
        ],
        ("Male", "Wisdom", "Any", "≤5"): [
            ("Everyman", 25.81),
            ("Lone Wolf", 19.35),
            ("Meddler", 19.35),
            ("Klutz", 12.90),
            ("Plugger", 12.90),
            ("Daydreamer", 9.68),
        ],

        ("Male", "Luck", "Any", "≥12"): [
            ("Lucky Devil", 80.00),
            ("Happy Camper", 20.00),
        ],
        ("Male", "Luck", "Any", "6–11"): [
            ("Happy Camper", 27.27),
            ("Free Spirit", 18.18),
            ("Meddler", 18.18),
            ("Narcissist", 18.18),
            ("Spoilt Brat", 18.18),
        ],
        ("Male", "Luck", "Any", "≤5"): [
            ("Everyman", 25.00),
            ("Crybaby", 18.75),
            ("Lout", 18.75),
            ("Good Egg", 12.50),
            ("Show-Off", 12.50),
            ("Straight Arrow", 12.50),
        ],

        #------------------ FEMALE ------------------#
        ("Female", "Strength", "Any", "≥11"): [
            ("Idealist", 26.09),
            ("Meathead", 26.09),
            ("Tomboy", 26.09),
            ("Sore Loser", 21.74),
        ],
        ("Female", "Strength", "Any", "≤10"): [
            ("Acrobat", 37.50),
            ("Clown", 37.50),
            ("Scatterbrain", 25.00),
        ],
        ("Female", "Strength", "Any", "≤10"): [
            ("Amazon", 40.00),
            ("Daredevil", 33.33),
            ("Thug", 26.67),
        ],
        ("Female", "Strength", "Any", "≤10"): [
            ("Lone Wolf", 44.44),
            ("Genius", 33.33),
            ("Slippery Devil", 22.22),
        ],
        ("Female", "Strength", "Any", "≤10"): [
            ("Everyman", 28.57),
            ("Narcissist", 21.43),
            ("Crybaby", 14.29),
            ("Daydreamer", 14.29),
            ("Socialite", 14.29),
            ("Spoilt Brat", 7.14),
        ],

        ("Female", "Agility", "Any", "≥12"): [
            ("Acrobat", 42.86),
            ("Bat Out of Hell", 42.86),
            ("Daredevil", 14.29),
        ],
        ("Female", "Agility", "Any", "7–11"): [
            ("Scatterbrain", 34.78),
            ("Acrobat", 26.09),
            ("Sore Loser", 21.74),
            ("Narcissist", 17.39),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Idealist", 25.00),
            ("Lone Wolf", 25.00),
            ("Thug", 25.00),
            ("Tomboy", 25.00),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Everyman", 34.48),
            ("Klutz", 20.69),
            ("Show-Off", 20.69),
            ("Socialite", 13.79),
            ("Crybaby", 10.34),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Slippery Devil", 50.00),
            ("Clown", 37.50),
            ("Contrarian", 12.50),
        ],

        ("Female", "Resilience", "Any", "≥10"): [
            ("Ironclad", 50.00),
            ("Tough Cookie", 50.00),
        ],
        ("Female", "Resilience", "Any", "6–9"): [
            ("Drudge", 33.33),
            ("Mule", 33.33),
            ("Plugger", 33.33),
        ],
        ("Female", "Resilience", "Any", "≤5"): [
            ("Gourmand", 38.46),
            ("Meathead", 38.46),
            ("Free Spirit", 23.08),
        ],
        ("Female", "Resilience", "Any", "≤5"): [
            ("Everyman", 29.41),
            ("Lazybones", 17.65),
            ("Meddler", 17.65),
            ("Shrinking Violet", 17.65),
            ("Straight Arrow", 17.65),
        ],

        ("Female", "Wisdom", "Any", "≥10"): [
            ("Genius", 80.00),
            ("Wit", 20.00),
        ],
        ("Female", "Wisdom", "Any", "6–9"): [
            ("Slippery Devil", 40.00),
            ("Wit", 26.67),
            ("Egghead", 20.00),
            ("Show-Off", 13.33),
        ],
        ("Female", "Wisdom", "Any", "≤5"): [
            ("Everyman", 25.81),
            ("Lone Wolf", 19.35),
            ("Meddler", 19.35),
            ("Klutz", 12.90),
            ("Plugger", 12.90),
            ("Daydreamer", 9.68),
        ],

        ("Female", "Luck", "Any", "≥12"): [
            ("Happy Camper", 100.00),
        ],
        ("Female", "Luck", "Any", "6–11"): [
            ("Happy Camper", 27.27),
            ("Free Spirit", 18.18),
            ("Meddler", 18.18),
            ("Narcissist", 18.18),
            ("Spoilt Brat", 18.18),
        ],
        ("Female", "Luck", "Any", "≤5"): [
            ("Everyman", 25.00),
            ("Crybaby", 18.75),
            ("Lout", 18.75),
            ("Good Egg", 12.50),
            ("Show-Off", 12.50),
            ("Straight Arrow", 12.50),
        ],
    },
    "Gadabout": {
        #------------------ MALE ------------------#
        ("Male", "Strength", "Any", "≥11"): [
            ("Idealist", 35.29),
            ("Meathead", 35.29),
            ("Sore Loser", 29.41),
        ],
        ("Male", "Strength", "Any", "≤10"): [
            ("Acrobat", 37.50),
            ("Clown", 37.50),
            ("Scatterbrain", 25.00),
        ],
        ("Male", "Strength", "Any", "≤10"): [
            ("Daredevil", 55.56),
            ("Thug", 44.44),
        ],
        ("Male", "Strength", "Any", "≤10"): [
            ("Lone Wolf", 44.44),
            ("Genius", 33.33),
            ("Slippery Devil", 22.22),
        ],
        ("Male", "Strength", "Any", "≤10"): [
            ("Everyman", 28.57),
            ("Narcissist", 21.43),
            ("Crybaby", 14.29),
            ("Daydreamer", 14.29),
            ("Socialite", 14.29),
            ("Spoilt Brat", 7.14),
        ],
        ("Male", "Agility", "Any", "≥12"): [
            ("Acrobat", 42.86),
            ("Bat out of Hell", 42.86),
            ("Daredevil", 14.29),
        ],
        ("Male", "Agility", "Any", "7–11"): [
            ("Scatterbrain", 34.78),
            ("Acrobat", 26.09),
            ("Sore Loser", 21.74),
            ("Narcissist", 17.39),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Idealist", 33.33),
            ("Lone Wolf", 33.33),
            ("Thug", 33.33),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Everyman", 34.48),
            ("Klutz", 20.69),
            ("Show-Off", 20.69),
            ("Socialite", 13.79),
            ("Crybaby", 10.34),
        ],
        ("Male", "Agility", "Any", "≤6"): [
            ("Slippery Devil", 50.00),
            ("Clown", 37.50),
            ("Contrarian", 12.50),
        ],
        ("Male", "Resilience", "Any", "≥11"): [
            ("Gourmand", 33.33),
            ("Ironclad", 33.33),
            ("Toug Cookie", 33.33),
        ],
        ("Male", "Resilience", "Any", "6–10"): [
            ("Drudge", 33.33),
            ("Gourmand", 27.78),
            ("Mule", 22.22),
            ("Lothario", 16.67),
        ],
        ("Male", "Resilience", "Any", "≤5"): [
            ("Thug", 60.00),
            ("Daredevil", 40.00),
        ],
        ("Male", "Resilience", "Any", "≤5"): [
            ("Clown", 25.00),
            ("Everyman", 25.00),
            ("Lazybones", 25.00),
            ("Daydreamer", 12.50),
            ("Lone Wolf", 12.50),
        ],
        ("Male", "Wisdom", "Any", "≥10"): [
            ("Wit", 66.67),
            ("Genius", 33.33),
        ],
        ("Male", "Wisdom", "Any", "6–9"): [
            ("Clown", 33.33),
            ("Lothario", 25.00),
            ("Slippery Devil", 25.00),
            ("Egghead", 16.67),
        ],
        ("Male", "Wisdom", "Any", "≤5"): [
            ("Lazybones", 22.22),
            ("Free Spirit", 16.67),
            ("Spoilt Brat", 16.67),
            ("Everyman", 11.11),
            ("Lone Wolf", 11.11),
        ],
        ("Male", "Luck", "Any", "≥9"): [
            ("Lucky Devil", 100.00),
        ],
        ("Male", "Luck", "Any", "6–8"): [
            ("Happy camper", 36.36),
            ("Lout", 27.27),
            ("Lothario", 18.18),
            ("Spoilt Brat", 18.18),
        ],
        ("Male", "Luck", "Any", "≤5"): [
            ("Clown", 20.69),
            ("Lazybones", 20.69),
            ("Lothario", 20.69),
            ("Crybaby", 13.79),
            ("Narcissist", 10.34),
            ("Free Spirit", 6.90),
            ("Socialite", 6.90),
        ],

        #------------------ FEMALE ------------------#
        ("Female", "Strength", "Any", "≥11"): [
            ("Idealist", 26.09),
            ("Meathead", 26.09),
            ("Tomboy", 26.09),
            ("Sore Loser", 21.74),
        ],
        ("Female", "Strength", "Any", "≤10"): [
            ("Acrobat", 37.50),
            ("Clown", 37.50),
            ("Scatterbrain", 25.00),
        ],
        ("Female", "Strength", "Any", "≤10"): [
            ("Amazon", 40.00),
            ("Daredevil", 33.33),
            ("Thug", 26.67),
        ],
        ("Female", "Strength", "Any", "≤10"): [
            ("Lone Wolf", 44.44),
            ("Genius", 33.33),
            ("Slippery Devil", 22.22),
        ],
        ("Female", "Strength", "Any", "≤10"): [
            ("Everyman", 28.57),
            ("Narcissist", 21.43),
            ("Crybaby", 14.29),
            ("Daydreamer", 14.29),
            ("Socialite", 14.29),
            ("Spoilt Brat", 7.14),
        ],
        ("Female", "Agility", "Any", "≥12"): [
            ("Acrobat", 42.86),
            ("Bat Out of Hell", 42.86),
            ("Daredevil", 14.29),
        ],
        ("Female", "Agility", "Any", "7–11"): [
            ("Scatterbrain", 34.78),
            ("Acrobat", 26.09),
            ("Sore Loser", 21.74),
            ("Narcissist", 17.39),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Idealist", 25.00),
            ("Lone Wolf", 25.00),
            ("Thug", 25.00),
            ("Tomboy", 25.00),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Everyman", 34.48),
            ("Klutz", 20.69),
            ("Show-Off", 20.69),
            ("Socialite", 13.79),
            ("Crybaby", 10.34),
        ],
        ("Female", "Agility", "Any", "≤6"): [
            ("Slippery Devil", 50.00),
            ("Clown", 37.50),
            ("Contrarian", 12.50),
        ],
        ("Female", "Resilience", "Any", "≥11"): [
            ("Gourmand", 33.33),
            ("Ironclad", 33.33),
            ("Tough Cookie", 33.33),
        ],
        ("Female", "Resilience", "Any", "6–10"): [
            ("Drudge", 40.00),
            ("Gourmand", 33.33),
            ("Mule", 26.67),
        ],
        ("Female", "Resilience", "Any", "≤5"): [
            ("Thug", 60.00),
            ("Daredevil", 40.00),
        ],
        ("Female", "Resilience", "Any", "≤5"): [
            ("Clown", 20.00),
            ("Everyman", 20.00),
            ("Lazybones", 20.00),
            ("Vamp", 20.00),
            ("Daydreamer", 10.00),
            ("Lone Wolf", 10.00),
        ],
        ("Female", "Wisdom", "Any", "≥10"): [
            ("Wit", 66.67),
            ("Genius", 33.33),
        ],
        ("Female", "Wisdom", "Any", "6–9"): [
            ("Clown", 30.77),
            ("Vamp", 30.77),
            ("Slippery Devil", 23.08),
            ("Egghead", 15.38),
        ],
        ("Female", "Wisdom", "Any", "≤5"): [
            ("Lazybones", 22.22),
            ("Free Spirit", 16.67),
            ("Spoilt Brat", 16.67),
            ("Everyman", 11.11),
            ("Lone Wolf", 11.11),
        ],
        ("Female", "Luck", "Any", "≥9"): [
            ("Princess", 100.00),
        ],
        ("Female", "Luck", "Any", "6–8"): [
            ("Happy Camper", 36.36),
            ("Lout", 27.27),
            ("Spoilt Brat", 18.18),
            ("Vamp", 18.18),
        ],
        ("Female", "Luck", "Any", "≤5"): [
            ("Clown", 20.69),
            ("Lazybones", 20.69),
            ("Vamp", 20.69),
            ("Crybaby", 13.79),
            ("Narcissist", 10.34),
            ("Free Spirit", 6.90),
            ("Socialite", 6.90),
        ],
    }
}